- project:
    name: ta-caas-security-amd64
    project: ta/caas-security
    project-name: ta-caas-security-amd64
    project-type:
        - merge
        - verify
    build-node: centos7-builder-2c-1g
    stream: master
    jobs:
      - akraino-project-stream-type-ta

- project:
    name: ta-caas-security-arm64
    project: ta/caas-security
    project-name: ta-caas-security-arm64
    project-type:
        - merge
        - verify
    build-node: aarch64_build
    gerrit-skip-vote: true
    arch: arm64
    stream: master
    jobs:
      - akraino-project-stream-type-ta
