- project:
    name: ta-config-manager-amd64
    project: ta/config-manager
    project-name: ta-config-manager-amd64
    project-type:
        - merge
        - verify
    build-node: centos7-builder-2c-1g
    stream: master
    jobs:
      - akraino-project-stream-type-ta

- project:
    name: ta-config-manager-arm64
    project: ta/config-manager
    project-name: ta-config-manager-arm64
    project-type:
        - merge
        - verify
    build-node: aarch64_build
    arch: arm64
    stream: master
    jobs:
      - akraino-project-stream-type-ta
