- project:
    name: ta-config-manager
    project: ta/config-manager
    project-name: ta-config-manager
    project-type:
        - merge:
            post_build_trigger:
              - project: 'ta-ci-build'
                condition: UNSTABLE_OR_BETTER
                trigger-with-no-params: true
        - verify
    build-node: centos7-builder-2c-1g
    stream: master
    jobs:
      - akraino-project-stream-type-ta
