---
- project:
    name: ta-os-net-config-amd64
    project: ta/os-net-config
    project-name: ta-os-net-config-amd64
    project-type:
      - merge
      - verify
    build-node: centos7-builder-2c-1g
    stream: master
    jobs:
      - akraino-project-stream-type-ta

- project:
    name: ta-os-net-config-arm64
    project: ta/os-net-config
    project-name: ta-os-net-config-arm64
    project-type:
      - merge
      - verify
    build-node: aarch64_build
    arch: arm64
    stream: master
    jobs:
      - akraino-project-stream-type-ta
