---
- project:
    name: security-project-view
    project-name: security
    views:
      - project-view

- project:
    name: security-info
    project: security
    project-name: security
    build-node: centos7-builder-2c-1g
    jobs:
      - gerrit-info-yaml-verify
